# install docker.
- name: install docker
  command: amazon-linux-extras install docker -y
  tags:
    - setup

# configure docker.
- name: configure docker
  copy:
    src: docker/daemon.json
    dest: "{{kubernetes.docker.conf_dir}}/daemon.json"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart docker
  tags:
    - setup

# enable docker service at boot.
- name: enable docker service at boot
  command: systemctl enable docker.service
  tags:
    - setup

# enable netfilter kernel module.
- name: enable netfilter kernel module
  command: modprobe br_netfilter
  tags:
    - setup

# set required network and swap kernel params.
- name: set required network and swap kernel params
  copy:
    src: kernel.conf
    dest: /etc/sysctl.d/kubernetes.conf
    owner: root
    group: root
    mode: 0600
  tags:
    - setup

# apply required network and swap kernel params.
- name: apply required network and swap kernel params
  command: sysctl --system
  tags:
    - setup

# add kubernetes repository to package manager source list.
- name: add kubernetes repository to package manager source list
  copy:
    src: yum.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0600
  tags:
    - setup

# install kubernetes packages from repository.
- name: install kubernetes packages from repository
  yum:
    name:
      - kubelet-{{kubernetes.version}}
      - kubeadm-{{kubernetes.version}}
      - kubectl-{{kubernetes.version}}
    state: present
    disable_excludes: kubernetes
  tags:
    - setup

# create kubernetes client configuration directory.
- name: create kubernetes client configuration directory
  file:
    path: "{{kubernetes.client.conf_dir}}"
    state: directory
    owner: ec2-user
    group: ec2-user
    recurse: true
    mode: 0755
  tags:
    - setup

# install git.
- name: install git
  yum:
    name: git
    state: present
  tags:
    - setup
