# start docker.
- name: start docker
  command: systemctl start docker.service
  tags:
    - start

# start kubernetes agent.
- name: start kubernetes agent
  command: systemctl start kubelet.service
  tags:
    - start
