apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - deployments
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - ingress
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
